let users = [];
let loggedInUser = [];
let activeUserTasks = [];
// let contacts = [
//   {
//     email: "anna@dev.com",
//     id: "OGMwWIk1wZRNpgViWj1",
//     color: "#45A7B2",
//     createdAt: "2025-01-12T00:37:50.096Z",
//     name: "Anna Greta",
//     password: "anna",
//     phone: "234567891098",
//   },
//   {
//     email: "bob@dev.com",
//     id: "OGMwWIk1wZRNpgViWj2",
//     color: "#A7B245",
//     createdAt: "2025-01-12T00:38:50.096Z",
//     name: "Bob Der Baumeister",
//     password: "bob",
//     phone: "234567811111",
//   },
//   {
//     email: "charlie@dev.com",
//     id: "OGMwWIk1wZRNpgViWj3",
//     color: "#B245A7",
//     createdAt: "2025-01-12T00:39:50.096Z",
//     name: "Charlie Sheen",
//     password: "charlie",
//     phone: "234567822222",
//   },
//   {
//     email: "david@dev.com",
//     id: "OGMwWIk1wZRNpgViWj4",
//     color: "#45B2A7",
//     createdAt: "2025-01-12T00:40:50.096Z",
//     name: "David Goliat",
//     password: "david",
//     phone: "234567833333",
//   },
//   {
//     email: "eva@dev.com",
//     id: "OGMwWIk1wZRNpgViWj5",
//     color: "#B2A745",
//     createdAt: "2025-01-12T00:41:50.096Z",
//     name: "Eva Adam",
//     password: "eva",
//     phone: "234567844444",
//   },
//   {
//     email: "frank@dev.com",
//     id: "OGMwWIk1wZRNpgViWj6",
//     color: "#A745B2",
//     createdAt: "2025-01-12T00:42:50.096Z",
//     name: "Frank Enstein",
//     password: "frank",
//     phone: "234567855555",
//   },
//   {
//     email: "grace@dev.com",
//     id: "OGMwWIk1wZRNpgViWj7",
//     color: "#B2B245",
//     createdAt: "2025-01-12T00:43:50.096Z",
//     name: "Grace Anatomie",
//     password: "grace",
//     phone: "234567866666",
//   },
//   {
//     email: "henry@dev.com",
//     id: "OGMwWIk1wZRNpgViWj8",
//     color: "#45A745",
//     createdAt: "2025-01-12T00:44:50.096Z",
//     name: "Henry Lamotte",
//     password: "henry",
//     phone: "234567877777",
//   },
//   {
//     email: "ivy@dev.com",
//     id: "OGMwWIk1wZRNpgViWj9",
//     color: "#A745A7",
//     createdAt: "2025-01-12T00:45:50.096Z",
//     name: "Ivy Hugo",
//     password: "ivy",
//     phone: "234567888888",
//   },
//   {
//     email: "jack@dev.com",
//     id: "OGMwWIk1wZRNpgViWj10",
//     color: "#B24545",
//     createdAt: "2025-01-12T00:46:50.096Z",
//     name: "Jack Sparrow",
//     password: "jack",
//     phone: "234567899999",
//   },
// ];

// let tasks = [
//   {
//     id: "abc123",
//     title: "JOIN Project",
//     description: "Join ist ein Kanban Board für eine Gruppe von Entwicklern.",
//     assigned_to: [contacts[5], contacts[7], contacts[3]],
//     category: "technical-tasks",
//     creator: "guest",
//     due_date: "2025-01-11",
//     prio: "urgent",
//     state: "awaitFeedback",
//     subtasks: [
//       { id: 1, content: "Create HTML Files", status: "open" },
//       { id: 2, content: "Create CSS Files", status: "closed" },
//     ],
//   },
//   {
//     id: "def456",
//     title: "Geburtstag Hannes",
//     description: "Hannes wird am 15.02.2025 geboren.",
//     assigned_to: [contacts[2], contacts[3], contacts[4]],
//     category: "user-story",
//     creator: "guest",
//     due_date: "2025-02-15",
//     prio: "medium",
//     state: "inProgress",
//     subtasks: [{ id: 1, content: "Windeltorte kaufen", status: "open" }],
//   },
//   {
//     id: "ghi789",
//     title: "Projektabschlussbericht erstellen",
//     description: "Den endgültigen Bericht für das Projekt Zertifizierung Produkte fertigstellen.",
//     assigned_to: [contacts[5]],
//     category: "technical-tasks",
//     creator: "guest",
//     due_date: "2025-03-20",
//     prio: "low",
//     state: "done",
//     subtasks: [
//       { id: 1, content: "Zertifiezierungskatalog in Programm einfügen", status: "open" },
//       { id: 2, content: "Risikomanagementteam und Krisenstab zusammenrufen", status: "open" },
//       { id: 3, content: "Qualitätsmanagementteam aktivieren", status: "closed" },
//       { id: 4, content: "Team aufstellen für Fragenkatalog", status: "open" },
//     ],
//   },
//   {
//     id: "jkl012",
//     title: "finance",
//     description: "Budget für das kommende Jahr planen.",
//     assigned_to: [contacts[6], contacts[7]],
//     category: "user-story",
//     creator: "guest",
//     due_date: "2025-04-10",
//     prio: "urgent",
//     state: "awaitFeedback",
//     subtasks: [
//       { id: 1, content: "Verbrauch 2024", status: "open" },
//       { id: 2, content: "Eigenbedarf 2024", status: "open" },
//     ],
//   },
//   {
//     id: "mno345",
//     title: "Marketingstrategie Q2 2025",
//     description: "Marketingstrategie für das zweite Quartal 2025 entwickeln.",
//     assigned_to: [contacts[8]],
//     category: "technical-tasks",
//     creator: "guest",
//     due_date: "2025-05-30",
//     prio: "medium",
//     state: "inProgress",
//     subtasks: [
//       { id: 1, content: "Marktanalyse", status: "closed" },
//       { id: 2, content: "Strategie-Dokument erstellen", status: "closed" },
//     ],
//   },
//   {
//     id: "pqr678",
//     title: "Software-Update Version 3.2.1",
//     description: "Neues Software-Update implementieren und testen.",
//     assigned_to: [contacts[9]],
//     category: "user-story",
//     creator: "guest",
//     due_date: "2025-06-15",
//     prio: "low",
//     state: "done",
//     subtasks: [
//       { id: 1, content: "Version 3.2.1 kompilieren", status: "open" },
//       { id: 2, content: "Code-Überprüfung", status: "open" },
//       { id: 3, content: "Fehler finden und korrigieren", status: "open" },
//     ],
//   },
//   {
//     id: "stu901",
//     title: "Wartungsarbeiten am Server",
//     description: "Regelmäßige Wartungsarbeiten am Server durchführen.",
//     assigned_to: [contacts[0], contacts[1], contacts[2]],
//     category: "technical-tasks",
//     creator: "guest",
//     due_date: "2025-07-25",
//     prio: "urgent",
//     state: "awaitFeedback",
//     subtasks: [
//       { id: 1, content: "Team informieren das Server gewartet wird", status: "open" },
//       { id: 2, content: "Server wieder starten", status: "open" },
//       { id: 3, content: "Server Wartungsprotokoll ausfüllen und abspeichern", status: "open" },
//     ],
//   },
//   {
//     id: "vwx234",
//     title: "Benutzerhandbuch erstellen",
//     description: "Benutzerhandbuch für das Projekt erstellen.",
//     assigned_to: [contacts[3]],
//     category: "user-story",
//     creator: "guest",
//     due_date: "2025-08-15",
//     prio: "medium",
//     state: "toDo",
//     subtasks: [
//       { id: 1, content: "Benutzerhandbuch erstellen", status: "open" },
//       { id: 2, content: "Übersetzungen durchführen", status: "open" },
//       { id: 3, content: "Testen und korrigieren", status: "open" },
//     ],
//   },
//   {
//     id: "yzab567",
//     title: "Kundenbefragung Q1 2025",
//     description: "Durchführung einer Kundenbefragung für das kommende Quartal 2025.",
//     assigned_to: [contacts[4], contacts[5]],
//     category: "technical-tasks",
//     creator: "guest",
//     due_date: "2025-09-30",
//     prio: "low",
//     state: "toDo",
//     subtasks: [
//       { id: 1, content: "Fragebogen erstellen", status: "open" },
//       { id: 2, content: "Kunden auswählen", status: "closed" },
//     ],
//   },
//   {
//     id: "cdef890",
//     title: "Website-Launch",
//     description: "Neues Website-Launch durchführen und präsentieren.",
//     assigned_to: [contacts[6], contacts[7], contacts[8]],
//     category: "user-story",
//     creator: "guest",
//     due_date: "2025-10-20",
//     prio: "urgent",
//     state: "toDo",
//     subtasks: [
//       { id: 1, content: "Website-Design erstellen", status: "open" },
//       { id: 2, content: "Website-Entwicklung", status: "open" },
//       { id: 3, content: "Website-Veröffentlichen", status: "open" },
//     ],
//   },
// ];
